name: CI

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: actions/checkout@v2

      - name: Install packages
        run: npm install

      - name: Test
        run: npm run test:ci

      - name: Build
        run: npm run build
